<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="barrachina-SONDRA" name="pytest" skipped="0" tests="1" time="9.575" timestamp="2021-01-25T19:55:19.565076"><testcase classname="" name="" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/home/barrachina/anaconda3/envs/tf-2-gpu/lib/python3.7/site-packages/py/_path/common.py", line 273, in relto
    strself = self.strpath
KeyboardInterrupt</error></testcase></testsuite></testsuites>